baseURL = 'https://jbandlow.github.io/'
languageCode = 'en-us'
title = "Jason Bandlow's Page"
theme = 'hugo-bearblog'
enableRobotsTXT = false

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "Jason Bandlow's Page"
  author = "Jason Bandlow"
